config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #resources :lists 

  resources :users do
  	resources :lists, :controller => "user_lists"

  end
  	
  root "users#index"
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
	serialize :notes
	serialize :status
	validates_presence_of :title, :due, :notes, :status, :user_id
	belongs_to :user, optional: true
end

app/models/user.rb
class User < ApplicationRecord

	validates_presence_of :account, :password, :nickname, :sex, :birth
	has_many :lists
	has_many :user_eventships
	has_many :events, :through => :user_eventships

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session,
      if: Proc.new { |c| c.request.format =~ %r{application/json} }
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
	before_action :set_list, :only => [:edit, :update, :destroy]
	def index

		@time = Time.now
		@lists = List.order("due ASC")
		if Selectparam.count == 0

			e = Selectparam.new(params: 0)
			e.save

		end	
		@select = Selectparam.first
		if @select[:params] != 0 
			if List.find(@select[:params])!= nil
				@list = List.find(@select[:params])
				@sum = ((@list.due).year - @time.year) * 400 + ((@list.due).month - @time.month) * 30 + ((@list.due).day - @time.day)
			else
				@list = nil
			end

		end
		@complete_array = []
		@lists.each do |e|
			 
			complete_rate = 0.0
			e[:status].each do |i|

				if i == true
					complete_rate += 1
					
				end
					
			end

		complete_rate = (complete_rate / (e[:notes].count)) * 100
				
		@complete_array.append(complete_rate)
		end
		
	end
	def new

		@list = List.new


	end
	def create
		
		notes_to_array
		status_init
		
		@list = List.new(list_params)

		
		
		if @list.save 
			@list.save
			redirect_to lists_path
		else
			render :action => :new
		end


	end
	def show
		
		@selectparams = Selectparam.first
		@selectparams.params = params[:id]
		
		@selectparams.save
		redirect_to lists_path

		
	end
	def edit
		@list[:notes] = (@list[:notes]).join("\r\n")
		
	end
	def update
		
		statusarray = @list.status
		if params[:commit] == "Check"
			
			if 	params[:status] != nil			
				
				(params[:status]).each do |p|

					statusarray[p.to_i] = true

				end
				
				@list.status = statusarray
				
			end	
			@list.save
			redirect_to lists_path

		else
			notes_to_array
			
			if @list.update_attributes(list_params)
			
				redirect_to lists_path
			else
				@list[:notes] = (@list[:notes]).join("\r\n")
				render :action => :edit
			end
		end
		
	end

	def destroy

		@list.destroy
		@select = Selectparam.first
		@select[:params] = 0
		@select.save
		redirect_to lists_path
		
	end

	private

	def list_params

		params.require(:list).permit(:title, :due, :notes => [], :status => [])
		

	end
	
	def set_list
		@list = List.find(params[:id])
		
	end

	def notes_to_array
		e = params[:list]
		e[:notes] = e[:notes].split(%r{\r\n*})
				
	end
	def status_init

		e = params[:list]
		e[:status] = Array.new((e[:notes]).count, "false")
		
	end
	def status_params

		
	end
end

app/controllers/user_lists_controller.rb
class UserListsController < ApplicationController

	before_action :set_list
	before_action :authenticate
	def index

		
		
		set_list
		@complete_array = []
		if @lists != nil
			@lists.each do |e|
				 
				complete_rate = 0.0
				e[:status].each do |i|

					if i == true
						complete_rate += 1
						
					end
						
				end
			

				complete_rate = (complete_rate / (e[:notes].count)) * 100
					
				@complete_array.append(complete_rate)
			end
		end
		
		

	end

	def new

		@list = List.new


	end
	def create
		
		notes_to_array
		status_init
		params[:list][:user_id] = session[:uid]
		
		@list = List.new(list_params)
		
		
		
		if @list.save 
			@list.save
			redirect_to user_lists_path(session[:uid])
		else
			render :action => :new
		end


	end
	def show
		
		
		session[:select] = params[:id].to_i
		
		
		redirect_to :action => :index

		
	end
	def edit
		@list[:notes] = (@list[:notes]).join("\r\n")
		
	end
	def update
		
		statusarray = @list.status
		if params[:commit] == "Check"
			
			if 	params[:status] != nil			
				
				(params[:status]).each do |p|

					statusarray[p.to_i] = true

				end
				
				@list.status = statusarray
				
			end	
			@list.save
			redirect_to user_lists_path(session[:uid])

		else
			notes_to_array
			
			if @list.update_attributes(list_params)
			
				redirect_to user_lists_path(session[:uid])
			else
				render :action => :edit
			end
		end
		
	end

	def destroy

		@list.destroy
		session[:select] = nil
		redirect_to user_lists_path(session[:uid])
		
	end

	private

	def list_params

		params.require(:list).permit(:title, :due, :user_id, :notes => [], :status => [])
		

	end
	
	def set_list

		@time = Time.now
		@lists = (List.where(user_id: session[:uid] )).order("due ASC")
		if session[:select] != nil && (List.find(session[:select].to_i))[:user_id] == session[:uid]

			@list = List.find(session[:select].to_i)
			@sum = ((@list.due).year - @time.year) * 400 + ((@list.due).month - @time.month) * 30 + ((@list.due).day - @time.day)			
			
		end
		
	end

	def notes_to_array
		e = params[:list]
		e[:notes] = e[:notes].split(%r{\r\n*})
				
	end
	def status_init

		e = params[:list]
		e[:status] = Array.new((e[:notes]).count, "false")
		
	end
	def authenticate

		if session[:uid] == nil || session[:uid] == params[:user_id]

			
			redirect_to users_path

		end

	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		session[:uid] = nil
		session[:select] = nil
	end

	def create
		@users = User.all
		@error = ""
		if params[:commit] == "login"

			if params[:login][:account] != "" && params[:login][:password] != "" 
				
				@user = User.find_by( account: params[:login] [:account])
				if @user 
					
					authenticate(params[:login][:password])

					respond_to do |f|

						@lists = List.where("user_id = #{@user.id}")
						f.json { render :json => {:user => @user, :list => @lists}}
						f.html { redirect_to user_lists_path(session[:uid])}

					end

							
				
				else

					@error = "Account or password is not correct"
					render :action => :index						

				end
				
			else

				@error = "Account or password can't be blank!"
				render :action => :index

			end

		else

			@user = User.new(sign_up_params)
			if @user.save

				redirect_to :action => :index

			else

				render :action => :new

			end

			
			
			

		end

	end

	def new


		
	end

	private

	def authenticate(password)
		
		 if password == @user[:password]

		 	session[:account] = @user.account
		 	session[:uid] = @user.id

		 end

	end

	def sign_up_params

		params.require(:sign_up).permit(:account, :password, :nickname, :sex, :birth)
		
	end
		
	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_lists_helper.rb
module UserListsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToDoList</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/edit.html.erb
<div class="errormessage">
	<% if @list.errors.present? %>

		<ul>
			
			<% @list.errors.each do |error, message| %>

				<li><%= "#{error.capitalize} #{message}" %></li>

			<% end %>

		</ul>

	<% end %>
</div>

<div class="container form">
	<%= form_for @list, :url => {:controller => :lists, :action => :update, :method => :patch} do |f| %>
	<div class="form-group ">
		<%= f.label :title %>
		<%= f.text_field :title, class: "form-control" %>	
	</div>
	<div class="form-group">
		<%= f.label :due %>
		<%= f.text_field :due, class: "form-control" %>
	</div>
	<div class="form-group">
		
		<%= f.label :notes %>
	
		<%= f.text_area :notes, class: "form-control" %>

	</div>
	<div class=" form">
		<a href=<%=lists_path %>><button>cancel</button></a>
		
		<%= f.submit "Update", class:"float-right" %>
	</div>
	<% end %>
</div>

<% if @list.errors.present? %>
<ul>
	<% @list.errors.each do |error, message| %>
	<li>
		<%= "#{error.capitalize} #{message}" %>
	</li>
	<% end %>
</ul>
<% end %>

app/views/lists/index.html.erb
<div id = "banner" class="container navbar-fixed-top">
	<div id = "left" class=" col-xs-6 col-sm-6 col-md-6 col-lg-6">
		<div class="logo">
			<h1>To do List !</h1>
		</div>
		
	</div>
	<div id = "right" class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
		<div class="make-new-button">
			<%= link_to 'Make a new notes', new_list_path %>
		</div>
		
	</div>
</div>

<div class = "container list-show">
<table class="table-striped col-xs-12 col-sm-12 col-md-12 col-lg-12">
	<% if @lists.count == 0 %>
		<tr>
			<th>There is nothing in list</th>
		</tr>

		
	<% else %>
		<tr>
			<th>title</th>
			<th>due_date</th>
			<th>status</th>
			
		</tr>
		<% a_count = 0 %>
		<% @lists.each do |l|%>
			
			<tr>
				<td><%= l.title %></td>
				<td><%= l.due %></td>
				<td>
					<a href= <%= list_path(l) %>> 
							<%= @complete_array[a_count]%> %
					</a>
					<% a_count += 1%>
				</td>

				
			</tr>
		<% end %>
		
	<% end %>
</table>
</div>

<div class="notes_list container ">
		<% if @select.params == 0 %>
			<hr>
		<%elsif @list.notes != nil %>
			<hr>

			<table class="table-striped notes-list col-xs-12 col-sm-12 col-md-12 col-lg-12">
				<% if @sum > 0 %>

					<tr>
						<td>
							<a class = "btn" href= <%= edit_list_path(@list) %>><button>Edit</button></a>
									
							<a class = "btn" href= <%= list_path(@list) %> data-confirm = "Are you sure?" data-method = "delete" rel = "nofollow"><button>delet</button></a>
								</td>
							</tr>
				<%else %>
					<tr>
						<td>
							<h2>out of due time !</h2>
						</td>
					</tr>
				<% end %>
				
			</table>
			
		<% else %>
			<hr>
			<h1>There is no notes please edit it!</h1>
		<% end %>
	</div>
<div class="container">
	<% if @list != nil %>
		<div id = "status-check-box">
			<%= form_for @list do |f| %>
				
				<%= f.label :notes %>
				<%for i in 0..((@list.notes).count-1) %>
					
					<% if @list.status[i] != true %>	
						<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 padding-left">
							<input type="checkbox" name ="status[]" value = <%=i%>><%=@list.notes[i]%>
								
						</div>
					<%else %>
					<p><%= @list.notes[i] %></p>
					<% end %>
					

				<% end %>
				<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 form-btn-right">
						<%= f.submit "Check" %>
				</div>			
				
				
			<% end %>
		</div>
	<% end %>


</div>








	

app/views/lists/new.html.erb
<div class="container form">
<%= form_for @list, :url => lists_path, :method => :post do |f| %>
	<div class = "form-group">
		<%= f.label :title %>
		<%= f.text_field :title, class: "form-control" %>
	</div>
	<div class = "form-group">
		<%= f.label :due %>
		<%= f.text_field :due, class: "form-control" %>
	</div>
	<div class = "form-group">
		<%= f.label :notes %>
		<%= f.text_area :notes, class: "form-control" %>
	</div>

	<div>
		<a href= <%= lists_path %>><button>cancel</button></a>
		<%= f.submit "Creat" %>
	</div>
<% end %>	
</div>
<div class="errormessage">
	<% if @list.errors.present? %>

		<ul>
			
			<% @list.errors.each do |error, message| %>

				<li><%= "#{error.capitalize} #{message}" %></li>

			<% end %>

		</ul>

	<% end %>
</div>

app/views/user_lists/edit.html.erb
<div class="container form">
	<%= form_for @list, :url => user_list_path(session[:uid], session[:select]) do |f| %>
	<div class="form-group ">
		<%= f.label :title %>
		<%= f.text_field :title, class: "form-control" %>	
	</div>
	<div class="form-group">
		<%= f.label :due %>
		<%= f.text_field :due, class: "form-control" %>
	</div>
	<div class="form-group">
		
		<%= f.label :notes %>
	
		<%= f.text_area :notes, class: "form-control" %>

	</div>
	<div class=" form">
		<a href=<%=user_lists_path(session[:uid]) %>><button>cancel</button></a>
		
		<%= f.submit "Update", class:"float-right" %>
	</div>
	<% end %>
</div>

<% if @list.errors.present? %>
<ul>
	<% @list.errors.each do |error, message| %>
	<li>
		<%= "#{error.capitalize} #{message}" %>
	</li>
	<% end %>
</ul>
<% end %>

app/views/user_lists/index.html.erb
<div id = "banner" class="container navbar-fixed-top">
	<div id = "left" class=" col-xs-6 col-sm-6 col-md-6 col-lg-6">
		<div class="logo">
			<h1>To do List !</h1>
		</div>
		
	</div>
	<div id = "right" class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
		<div class="make-new-button">
			<%= link_to 'Make a new notes', new_user_list_path %>
		</div>
		<div class="make-new-button">
			<%= link_to 'log-out', users_path %>
		</div>
		
	</div>
</div>

<div class = "container list-show">
<table class="table-striped col-xs-12 col-sm-12 col-md-12 col-lg-12">
	<% if @lists == nil %>
		<tr>
			<th>There is nothing in list</th>
		</tr>

		
	<% else %>
		<tr>
			<th>title</th>
			<th>due_date</th>
			<th>status</th>
			
		</tr>
		<% a_count = 0 %>
		<% @lists.each do |l|%>
			
			<tr>
				<td><%= l.title %></td>
				<td><%= l.due %></td>
				<td>
					<a href= <%= user_list_path(session[:uid], l.id) %>> 
							<%= @complete_array[a_count]%> %
					</a>
					<% a_count += 1%>
				</td>

				
			</tr>
		<% end %>
		
	<% end %>
</table>
</div>

<div class="notes_list container ">
		
		<% if @list %>
			<hr>

			<table class="table-striped notes-list col-xs-12 col-sm-12 col-md-12 col-lg-12">
				<% if @sum > 0 %>

					<tr>
						<td>
							<a href= <%= edit_user_list_path(session[:uid], @list) %>><button class = "btn btn-primary">Edit</button></a>
									
							<a href= <%= user_list_path(session[:uid], @list) %> data-confirm = "Are you sure?" data-method = "delete" rel = "nofollow"><button class = "btn btn-primary">delet</button></a>
								</td>
							</tr>
				<%else %>
					<tr>
						<td>
							<h2>out of due time !</h2>
						</td>
						<td>
							<a href= <%= user_list_path(session[:uid], @list) %> data-confirm = "Are you sure?" data-method = "delete" rel = "nofollow"><button class = "btn btn-primary">delet</button></a>
								</td>
						</td>
					</tr>
				<% end %>
				
			</table>
			
		<% else %>
			<hr>
			<h1>There is no notes please edit it!</h1>
		<% end %>
	</div>
<div class="container">
	<% if @list != nil %>
		<div id = "status-check-box">
			<%= form_for @list, :url => user_list_path(session[:uid], session[:select]) do |f| %>
				
				<%= f.label :notes %>
				<%for i in 0..((@list.notes).count-1) %>
					
					<% if @list.status[i] != true %>	
						<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 padding-left">
							<input type="checkbox" name ="status[]" value = <%=i%>><%=@list.notes[i]%>
								
						</div>
					<%else %>
					<p><%= @list.notes[i] %></p>
					<% end %>
					

				<% end %>
				
				<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 form-btn-right">
						<%= f.submit "Check" %>
				</div>			
				
				
			<% end %>
		</div>
	<% end %>


</div>








	

app/views/user_lists/new.html.erb
<div class="container">
	<% if @list.errors.present? %>

		<ul>
			
			<% @list.errors.each do |error, message| %>

				<li>
					<%= "#{error.capitalize} #{message}" %>
				</li>

			<% end %>

		</ul>

	<% end %>

</div>
<div class="container form">
<%= form_for :list, :url => user_lists_path, :method => :post do |f| %>
	<div class = "form-group">
		<%= f.label :title %>
		<%= f.text_field :title, class: "form-control" %>
	</div>
	<div class = "form-group">
		<%= f.label :due %>
		<%= f.date_select :due, option = {:use_two_digit_numbers => true, :start_year => Date.today.year, :end_year => Date.today.year+5} %>
	</div>
	<div class = "form-group">
		<%= f.label :notes %>
		<%= f.text_area :notes, class: "form-control" %>
	</div>
	<div class = "form-group">
		<%= f.hidden_field :user_id, :value => session[:uid] %>
	
	</div>

	<div>
		<a href= <%= user_lists_path %>><button class="btn btn-primary">cancel</button></a>
		<%= f.submit "Creat", class: "btn btn-primary" %>
	</div>
<% end %>	
</div>

app/views/users/_banner.html.erb
<div id = "banner" class=" navbar-fixed-top">
	<div id = "left" class=" col-xs-6 col-sm-6 col-md-6 col-lg-6">
		<div class="logo">
			<h1>To do List !</h1>
		</div>
		
	</div>
	<div id = "right" class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
	
		<div class="make-new-button">
			
			<%= link_to 'Sign-up',new_user_path %>

		</div>
		
	</div>
</div>

app/views/users/index.html.erb
<%= render :partial => "banner" %>
<div class="container login">
	<div class="explain col-xs-6 col-sm-6 col-md-6 col-lg-6">
		<h1>List something need to be done!</h1>
		<ul>
			<li>Creat an account</li>
			<li>Make a new list</li>
			<li>Check the notes, if you have already done it</li>

		</ul>
	</div>
	<div class="login-form col-xs-6 col-sm-6 col-md-6 col-lg-6">
		<%= form_for :login, :url => users_path do |f| %>
			<div class="form-group form">
				<%= f.label :account %>
				<%= f.text_field :account, class: "form-control" %>
			</div>
			<div class="form-group form">
				<%= f.label :password %>
				<%= f.password_field :password, class: "form-control" %>
			</div>

			<%= f.submit "login", class: "btn btn-primary " %>
		

		<% end %>

		<% if @error != "" && @error != nil%>

		<p><%= @error %></p>
		

		<% end %>

	</div>

</div>

app/views/users/new.html.erb
<%= render :partial => "banner" %>
<div class="container form register-form">
<%= form_for :sign_up, :url => users_path, :method => :post do |f| %>
	<div class = "form-group">
		<%= f.label :account %>
		<%= f.text_field :account, class: "form-control" %>
	</div>
	<div class = "form-group">
		<%= f.label :password %>
		<%= f.password_field :password, class: "form-control" %>
	</div>
	<div class = "form-group">
		<%= f.label :nickname %>
		<%= f.text_field :nickname, class: "form-control" %>
	</div>
	<div class = "form-group">
		<%= f.label :sex %>
		<%= f.select :sex, options_for_select(["Man", "Woman"]), class: "form-control" %>
	</div>
	<div class = "form-group">
		<%= f.label :birth %>
		<%= f.date_select :birth, option = {:use_two_digit_numbers => true, :start_year => 1980, :end_year => Date.today.year } %>
	</div>

	<div>
		<a href= <%= users_path %>><button class="btn btn-primary">cancel</button></a>
		<%= f.submit "Sign_up", class: "btn btn-primary" %>
	</div>
<% end %>	
</div>